services:

  api-kukuplaza:
    container_name: api-kukuplaza
    build: .
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    container_name: mysql_db_kukuplaza
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_kukuplaza
    # volumes:
    #   - ./backups:/home/backups
    restart: unless-stopped
    ports:
    - 3300:3306
  
  phpmyadmin:
    container_name: phpmyadmin_kukuplaza
    image: phpmyadmin:5.2.1
    ports:
      - 8011:80
    environment:
      - PMA_ARBITRARY=1